name: app-configuration
base: &base
  server:
      SERVER_HOST: 0.0.0.0

  database:
    DATABASE_DRIVERNAME: postgresql+asyncpg
    DATABASE_ECHO: false
    DATABASE_POOL_MIN_SIZE: 1
    DATABASE_POOL_MAX_SIZE: 10
    DATABASE_SSL: false
    DATABASE_RETRY_LIMIT: 32
    DATABASE_RETRY_INTERVAL: 1

  jinja2:
    JINJA2_PACKAGE_NAME: app
    JINJA2_PACKAGE_PATH: templates
    JINJA2_ENCODING: utf-8


develop:
  <<: *base

testing:
  <<: *base

production:
  <<: *base

