name: app-configuration
base: &base
  version: 1.0.0

  server:
    SERVER_HOST: 0.0.0.0

  database:
    DATABASE_DRIVERNAME: postgresql+asyncpg
    DATABASE_ECHO: false
    DATABASE_POOL_MIN_SIZE: 1
    DATABASE_POOL_MAX_SIZE: 10
    DATABASE_SSL: false
    DATABASE_RETRY_LIMIT: 32
    DATABASE_RETRY_INTERVAL: 1

  jinja2:
    JINJA2_PACKAGE_NAME: app
    JINJA2_PACKAGE_PATH: templates
    JINJA2_ENCODING: utf-8

  logging:
    version: 1
    disable_existing_loggers: true
    formatters:
      standard:
        format: "[%(asctime)20s][PID %(process)d:%(threadName)s][%(name)s][%(levelname)s][MESSAGE]: %(message)s"

    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    root:
      level: NOTSET
      handlers: [ console ]
      propogate: yes

    loggers:
      app:
        level: INFO
        propogate: no

      algorithms.views:
        level: INFO
        propagate: no

develop:
  <<: *base

testing:
  <<: *base

production:
  <<: *base

