name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      CONFIG_PATH: ../../configuration.yaml
      ENVIRONMENT: testing

    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Checking pylint
        run: |
          pylint ./app/ ./tests/

      - name: Checking pytest
        run: |
          pytest
